server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/customer_db?useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: guerra2350

  sql:
    init:
      mode: never

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQLDialect
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
    defer-datasource-initialization: true