INSERT INTO country (country_code, country_name, iso_code) VALUES ('48', 'Polonia', 'PL');
INSERT INTO country (country_code, country_name, iso_code) VALUES ('1809', 'Republica Dominicana', 'DO');
INSERT INTO country (country_code, country_name, iso_code) VALUES ('1829', 'Republica Dominicana', 'DO');
INSERT INTO country (country_code, country_name, iso_code) VALUES ('1849', 'Republica Dominicana', 'DO');
INSERT INTO country (country_code, country_name, iso_code) VALUES ('51', 'Peru', 'PE');
INSERT INTO country (country_code, country_name, iso_code) VALUES ('52', 'Mexico', 'MX');
INSERT INTO country (country_code, country_name, iso_code) VALUES ('58', 'Venezuela', 'VE');
INSERT INTO country (country_code, country_name, iso_code) VALUES ('595', 'Paraguay', 'PY');
INSERT INTO country (country_code, country_name, iso_code) VALUES ('593', 'Ecuador', 'EC');
INSERT INTO country (country_code, country_name, iso_code) VALUES ('57', 'Colombia', 'CO');
INSERT INTO country (country_code, country_name, iso_code) VALUES ('506', 'Costa Rica', 'CR');
INSERT INTO country (country_code, country_name, iso_code) VALUES ('56', 'Paraguay', 'CL');
INSERT INTO country (country_code, country_name, iso_code) VALUES ('591', 'Bolivia', 'BO');
INSERT INTO country (country_code, country_name, iso_code) VALUES ('54', 'Argentina', 'AR');
INSERT INTO country (country_code, country_name, iso_code) VALUES ('53', 'Cuba', 'CU');
INSERT INTO country (country_code, country_name, iso_code) VALUES ('507', 'Panama', 'PA');
INSERT INTO country (country_code, country_name, iso_code) VALUES ('34', 'España', 'ES');
INSERT INTO country (country_code, country_name, iso_code) VALUES ('598', 'Uruguay', 'UY');
INSERT INTO country (country_code, country_name, iso_code) VALUES ('55', 'Brasil', 'BR');
INSERT INTO country (country_code, country_name, iso_code) VALUES ('504', 'Honduras', 'HN');
INSERT INTO country (country_code, country_name, iso_code) VALUES ('502', 'Guatemala', 'GT');
INSERT INTO country (country_code, country_name, iso_code) VALUES ('503', 'El Salvador', 'SV');
INSERT INTO country (country_code, country_name, iso_code) VALUES ('505', 'Nicaragua', 'NI');
INSERT INTO country (country_code, country_name, iso_code) VALUES ('19', 'Estados Unidos', 'US');
INSERT INTO country (country_code, country_name, iso_code) VALUES ('44', 'Reino Unido', 'GB');
INSERT INTO country (country_code, country_name, iso_code) VALUES ('353', 'Irlanda', 'IE');
INSERT INTO country (country_code, country_name, iso_code) VALUES ('212', 'Marruecos', 'MA');
INSERT INTO country (country_code, country_name, iso_code) VALUES ('33', 'Francia', 'FR');
INSERT INTO country (country_code, country_name, iso_code) VALUES ('63', 'Filipinas', 'PH');



INSERT INTO payment_method (bank, card_number, owner_name, payment_type) VALUES ('BCP', '19171550324053', 'Kevin Hidalgo', 'bcp');
INSERT INTO payment_method (bank, card_number, owner_name, payment_type) VALUES ('OXXO','4217 4700 6020 5412', '', 'oxxo2');
INSERT INTO payment_method (bank, card_number, owner_name, payment_type) VALUES ('OXXO','4217 4700 7061 2136', '', 'oxxo3');
INSERT INTO payment_method (bank, card_number, owner_name, payment_type) VALUES ('BANREGIO','4741 7429 4511 0792', '', 'oxxo7');
INSERT INTO payment_method (bank, card_number, owner_name, payment_type) VALUES ('INTERBANK','926 446 525', 'Kevin Hidalgo', 'plin');
INSERT INTO payment_method (bank, card_number, owner_name, payment_type) VALUES ('STP','646069206821330967', 'Karen Ontiveros Paredes', 'transferencia1');
INSERT INTO payment_method (bank, card_number, owner_name, payment_type) VALUES ('STP','646420146408376153', 'Alejandra Escalona Macedo', 'transferencia2');
INSERT INTO payment_method (bank, card_number, owner_name, payment_type) VALUES ('STP','646420146408836826', 'Fátima Esperanza Vázquez Vargas', 'transferencia3');
INSERT INTO payment_method (bank, card_number, owner_name, payment_type) VALUES ('INVEX','059180131110659220', 'Roberto Carlos Hernández Lino', 'transferencia4');
INSERT INTO payment_method (bank, card_number, owner_name, payment_type) VALUES ('INVEX','059180131110713373', 'Rutilo Hernandez Luna', 'transferencia5');
INSERT INTO payment_method (bank, card_number, owner_name, payment_type) VALUES ('INVEX','059180131111196232', 'MEDINA SOLIS NORMA LIBERTAD', 'transferencia6');
INSERT INTO payment_method (bank, card_number, owner_name, payment_type) VALUES ('BANREGIO','058597000061055436', 'Norma Medina Solis', 'transferencia7');
INSERT INTO payment_method (bank, card_number, owner_name, payment_type) VALUES ('BANREGIO','058597000061056396', 'Luna Hernandez Rutilo', 'transferencia8');
INSERT INTO payment_method (bank, card_number, owner_name, payment_type) VALUES ('INVEX','059180131111329805', 'CALVILLO PERALTA SOCORRO', 'transferencia9');
INSERT INTO payment_method (bank, card_number, owner_name, payment_type) VALUES ('BCP','926 446 525', 'Kevin Hidalgo', 'yape');
