version: "3.8"

services:
  mysqldb:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: guerra2350

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"